const statuses=['NIEUW','ANALYSE','TEST','OK','PARKEREN','AFGEKEURD','VERVALLEN'];
let state={items:[],categories:[],selected:null},initialized=false;
const selectedNumbers=new Set();
const $=id=>document.getElementById(id), csv=v=>String(v||'').split(',').map(x=>x.trim()).filter(Boolean);
const esc=x=>String(x).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function load(){const r=await fetch('/__opengraph_testmateriaal');if(!r.ok)throw Error('Start Graphlite via de lokale server.');state=await r.json();if(!initialized)setup();render();}
function setup(){initialized=true;statuses.forEach(x=>{$('status').add(new Option(x,x));$('statusFilter').add(new Option(x,x));$('bulkStatus').add(new Option(x,x))});$('bulkStatus').value='TEST';state.categories.forEach(x=>{$('category_code').add(new Option(`${x.code} · ${x.name}`,x.code));$('categoryFilter').add(new Option(`${x.code} · ${x.name}`,x.code))});['statusFilter','categoryFilter','search'].forEach(x=>$(x).addEventListener('input',render));$('selectVisible').addEventListener('change',e=>{visibleItems().forEach(x=>e.target.checked?selectedNumbers.add(x.number):selectedNumbers.delete(x.number));render()});$('applyBulkStatus').addEventListener('click',applyBulkStatus);}
function visibleItems(){const q=$('search').value.toLowerCase(),s=$('statusFilter').value,c=$('categoryFilter').value;return state.items.filter(x=>(!s||x.status===s)&&(!c||String(x.category_code)===c)&&(!q||x.original_input.toLowerCase().includes(q)||String(x.number).includes(q)));}
function updateBulkControls(items=visibleItems()){const selectedVisible=items.filter(x=>selectedNumbers.has(x.number)).length;$('selectedCount').textContent=`${selectedNumbers.size} geselecteerd`;$('selectVisible').checked=items.length>0&&selectedVisible===items.length;$('selectVisible').indeterminate=selectedVisible>0&&selectedVisible<items.length;$('applyBulkStatus').disabled=selectedNumbers.size===0;}
function render(){const items=visibleItems();$('count').textContent=`${items.length} van ${state.items.length}`;$('rows').innerHTML=items.map(x=>`<tr data-n="${x.number}"><td><input class="row-select" type="checkbox" aria-label="Selecteer ${x.number}" data-select-n="${x.number}" ${selectedNumbers.has(x.number)?'checked':''}></td><td>${x.number}</td><td>${esc(x.original_input)}</td><td>${x.category_code} · ${esc(x.category_name)}</td><td class="${x.status}">${x.status}</td><td>${x.analysis_status}</td></tr>`).join('');document.querySelectorAll('tr[data-n]').forEach(tr=>tr.onclick=e=>{if(!e.target.matches('input'))select(+tr.dataset.n)});document.querySelectorAll('[data-select-n]').forEach(box=>box.onchange=e=>{const n=+e.target.dataset.selectN;e.target.checked?selectedNumbers.add(n):selectedNumbers.delete(n);updateBulkControls(items)});updateBulkControls(items);}
async function applyBulkStatus(){const numbers=[...selectedNumbers].sort((a,b)=>a-b),status=$('bulkStatus').value;if(!numbers.length)return;const r=await fetch('/__opengraph_testmateriaal_bulk_status',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({numbers,status})}),j=await r.json();if(!r.ok){$('bulkMessage').textContent=`FOUT: ${j.error}`;return}$('bulkMessage').textContent=`${j.changed} van ${j.selected} gewijzigd naar ${j.status}`;selectedNumbers.clear();await load();}
function select(n){const x=state.items.find(item=>item.number===n);state.selected=x;$('heading').textContent=`${x.number} · revisie ${x.revision}`;$('editor').hidden=false;['original_input','category_code','sort_order','status','analysis_status','form','completion','internal_note'].forEach(k=>$(k).value=x[k]??'');$('features').value=x.features.join(', ');$('platforms').value=x.platforms.join(', ');$('publication_phase').value=x.publication_phase??'';$('kernels').value=x.kernels.map(k=>k.text).join('\n');$('relations').innerHTML=x.relations.length?x.relations.map(r=>`K${r.from_kernel}:${esc(r.from_referent)} ↔ K${r.to_kernel}:${esc(r.to_referent)} · ${esc(r.relation_type)}`).join('<br>'):'Geen cross-kernel-relaties';$('decision_rule').textContent=x.decision_rule;$('message').textContent='';}
$('editor').onsubmit=async e=>{e.preventDefault();const n=state.selected.number,p={};['original_input','category_code','sort_order','status','analysis_status','form','completion','publication_phase','internal_note'].forEach(k=>p[k]=$(k).value);['category_code','sort_order'].forEach(k=>p[k]=+p[k]);p.publication_phase=p.publication_phase===''?null:+p.publication_phase;p.features_json=csv($('features').value);p.platforms_json=csv($('platforms').value);p.kernels=$('kernels').value.split(/\r?\n/).map(x=>x.trim()).filter(Boolean);const r=await fetch(`/__opengraph_testmateriaal/${n}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(p)}),j=await r.json();if(!r.ok){$('message').textContent=`FOUT: ${j.error}`;return}$('message').textContent='Opgeslagen';await load();select(n);};
load().catch(e=>{document.querySelector('main').innerHTML=`<section class="card"><strong>Niet beschikbaar:</strong> ${esc(e.message)}</section>`});
